# Generated by Django 6.0.5 on 2026-06-05 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketRetrievalCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField(default=0.0)),
                ('candidate_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrieved_for', to='ticketing_system.ticket')),
                ('new_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_candidates', to='ticketing_system.ticket')),
            ],
            options={
                'ordering': ['-relevance_score'],
            },
        ),
    ]
