# Generated by Django 6.0.5 on 2026-06-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_system', '0002_ticketretrievalcandidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='RerankerTrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('candidate_text', models.TextField()),
                ('label', models.FloatField(help_text='1.0 for relevant, 0.0 for irrelevant')),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
