# Generated by Django 6.0.5 on 2026-06-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_system', '0004_ticket_triage_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed'), ('Resolved', 'Resolved')], default='Open', max_length=20),
        ),
    ]
