# Generated by Django 6.0.5 on 2026-06-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Agent', 'Human Agent'), ('Supervisor', 'Supervisor'), ('AI_Agent', 'AI System Agent')], default='Customer', max_length=20),
        ),
    ]
